### ISSUE TITLE
*_results.h5 not created after training

### ISSUE THREAD

**Issue by postpop** [janclemenslab/das#17]
Hi, I am trying training,prediction in das. 
I would like to ask you a question. I was unable to get the result.h5 file when I performed training with the das.train function in python. Test data has been prepared in step of making dataset.
Could you please tell me how I could do this?

_Originally posted by @yHamazaki84 in https://github.com/janclemenslab/das/issues/16#issuecomment-1000245443_

**Comment by postpop** [comment]
Hi @yHamazaki84,

I tested training using both the command line and `das.train.train()`. `_results.h5` files are created in both cases.

Do you get an error message? Can you share the full output produced during training? Thanks.

**Comment by yHamazaki84** [comment]
Thank you for reply.

I have created a dataset in the local environment, and trained it on the GPU server. After the training epoch is over,  I got the message "Killed" when I move to prediction, and it seems to end there.

```
Epoch 00020: val_loss did not improve from 0.02099
1000/1000 - 1356s - loss: 0.0027 - val_loss: 0.0264
INFO:root:re-loading last best model
INFO:root:predicting
Killed
```

I would like to ask one more question.
When I do a prediction using model, it seems that there is no prediction for the last few seconds?, is this something I could fix in the settings?

**Comment by postpop** [comment]
This looks like the job got killed on your server because of memory consumption or sth like that. Is that possible?

Regarding your other question: We already pad the end of the signals with zeros to ensure all samples have predictions but we currently use a simple heuristic to set the pad length. Maybe the padding is not long enough for your model. The easiest solution would be if you added a bunch of zeros to the end of the signal.

**Comment by yHamazaki84** [comment]
Thank you, it does indeed seem to be a memory problem with the server. I will look into it.
Apart from training, is there any way to output result.h5 using the test data provided in the making dataset step?

**Comment by postpop** [comment]
Hi,

this code will create all the variables in `results.h5`. We'll integrate this as a function into `DAS` in the future.

`savename` should point to the `*_model.h5` and `*_params.yaml` files of the model you want to test. For instance, if the model was saved to `results_folder/20211231_123456_model.h5` then `savename` should be `results_folder/20211231_123456`.

Hope this helps and let me know if you run into any issues.

```python
import das.utils, das.predict, das.evaluate, das.io

savename = '20211226_193037'
print('Loading last best model.')
model, params = das.utils.load_model_and_params(savename)

print(f"Loading data from {params['data_dir']}.")
d = das.io.load(params['data_dir'], x_suffix=params['x_suffix'], y_suffix=params['y_suffix'])

print('Predicting')
x_test, y_test, y_pred = das.evaluate.evaluate_probabilities(x=d['test']['x'], y=d['test']['y'],
                                                             model=model, params=params)

labels_test = das.predict.labels_from_probabilities(y_test)
labels_pred = das.predict.labels_from_probabilities(y_pred)

print('Evaluating')
conf_mat, report = das.evaluate.evaluate_segments(labels_test, labels_pred, params['class_names'], report_as_dict=True)
print(conf_mat)
print(report)
```

**Comment by yHamazaki84** [comment]
Thank you for your kind attention.
I tried the code you gave me, but it stopped again.
I tried it again on my local machine and got the following error. Is the test data set too large?

```
  File "C:\Users\***\anaconda3\envs\das\lib\site-packages\tensorflow\python\keras\engine\training_utils_v1.py", line 305, in finalize
    self.results = np.concatenate(self.results, axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate 13.2 GiB for an array with shape (107904, 16384, 2) and data type float32
```
Thank you in advance.

**Comment by postpop** [comment]
Looks like you have really big network - can you share the output of `model.summary()` here?

**Comment by yHamazaki84** [comment]
I hope there is enough information you need. Please let me know if there is a shortage.
Actually, I have not had enough try to consider the appropriate parameters for the network. If there is a parameter that is obviously too large, I would be happy to know about it. Thank you.

```
balance: false
batch_level_subsampling: false
batch_norm: true
batch_size: 64
class_names:
- noise
- call
class_types:
- segment
- segment
class_weights: null
data_dir: trainingdataset.npy
/trainingdataset"
data_hash: baaa3e6d3500bc67a9761ca524b9b609
data_padding: 96
data_splits:
  test: 0.2
  train: 0.6
  val: 0.2
delete_intermediate_store: true
event_std_seconds: 0.0016
file_split_dict: {}
file_splits: {}
filename_endsample_test: []
filename_endsample_train: []
filename_endsample_val: []
filename_startsample_test: []
filename_startsample_train: []
filename_startsample_val: []
filename_test: []
filename_train: []
filename_val: []
first_sample_train: 0
first_sample_val: 0
fraction_data: null
gap_seconds: 0.0
ignore_boundaries: true
kernel_size: 32
last_sample_train: null
last_sample_val: null
log_messages: true
make_single_class_datasets: false
model_name: tcn_stft
nb_channels: 1
nb_classes: 2
nb_conv: 3
nb_epoch: 400
nb_filters: 32
nb_freq: 1
nb_hist: 16384
nb_lstm_units: 0
nb_pre_conv: 4
nb_stacks: 2
neptune_api_token: null
neptune_project: null
output_stride: 1
pre_kernel_size: 3
pre_nb_conv: 2
pre_nb_dft: 64
pre_nb_filters: 16
reduce_lr: false
reduce_lr_patience: 5
return_sequences: true
sample_weight_mode: temporal
samplerate_x_Hz: 32000.0
samplerate_y_Hz: 32000.0
save_dir: trainingdataset.res
save_prefix: ''
seed: null
split_train_in_two: true
stride: 16192
tensorboard: true
use_separable: false
verbose: 2
version_data: true
with_y_hist: true
x_suffix: ''
y_offset: 0
y_suffix: ''

```
